name: Flutter CI/CD Pipeline

on:
  push:
    branches: [main]  # Trigger on main branch
  pull_request:
    branches: [main]  # Trigger on pull requests to main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is pulled

      - name: Debug - List Files
        run: ls -la  # Print directory structure to check pubspec.yaml

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.31.0-0.1.pre'
          channel: 'beta'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .  # Explicitly set project root

      - name: Run Tests
        run: flutter test --verbose

      - name: Build APK
        run: flutter build apk --release

  build-macOS:
    runs-on: macOS-latest
    needs: build-android  # Ensure Android build completes first

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug - List Files
        run: ls -la  # Print directory structure

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.31.0-0.1.pre'
          channel: 'beta'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .  # Explicitly set project root

      - name: Run Tests
        run: flutter test --verbose

      - name: Build macOS
        run: flutter build macos --release --verbose
